### ISSUE TITLE
发布和修改文章可指定发布时间

### ISSUE THREAD

**Issue by localvar** [b3log/pipe#106]
我在把以前的博客迁移到pipe上，由于pipe本身无法修改发布时间，导致文章都变成了最近刚发布的。目前，我通过直接改数据库暂时规避了问题，但很麻烦。另外，这个需求目前也可以通过导出、修改时间、重新导入来实现，但也很麻烦。故希望pipe直接支持。

**Comment by 88250** [comment]
你是怎么迁移的呢？如果通过 Markdown 导入的话是可以有历史存档的，比如 http://vanessa.b3log.org

**Comment by localvar** [comment]
原博客不支持markdown，所以手工迁移的。

**Comment by 88250** [comment]
哦，这就麻烦了..因为那个存档日期一旦生成改起来就有点麻烦了，对了，不要直接改库，不然各种关联会出错。

下个版本支持这个功能吧，在编辑文章的时候可以指定发布日期。

**Comment by localvar** [comment]
我已经改库了……

不太复杂的话，我可以帮着实现这个功能，不过我做后端比较多，前端只能写两行简单的js，没用过nodejs等

**Comment by 88250** [comment]
没事，我来搞吧，等下个版本发布后你可以尝试导出所有文章，然后删库重新初始化后导入。
