### ISSUE TITLE
未登录时不能访问中文标签

### ISSUE THREAD

**Issue by localvar** [b3log/pipe#109]
中文标签，如：

[http://blog.localvar.cn/tags/多线程](http://blog.localvar.cn/tags/多线程)

必须登录黑客派账号才能访问，但英文标签，如

[http://blog.localvar.cn/tags/C++](http://blog.localvar.cn/tags/C++)

就无此问题。

请使用”无痕浏览“的方式重现问题，仅仅是退出登陆状态是可以直接访问的。

**Comment by 88250** [comment]
这个主要是因为黑客派 SSO 的 bug，已经修復，谢谢反馈！
