### ISSUE TITLE
pipe发帖的时候输入框无法全部展示

### ISSUE THREAD

**Issue by zhanghuilon2017** [b3log/pipe#112]
https://github.com/b3log/pipe/issues/new
![image](https://user-images.githubusercontent.com/25762265/38712126-3a400934-3efc-11e8-8007-0072a943f520.png)

**Comment by 88250** [comment]
你用的浏览器是？

**Comment by zhanghuilon2017** [comment]
谷歌

**Comment by zhanghuilon2017** [comment]
哦，不是，是微信浏览器

**Comment by 88250** [comment]
@Vanessa219 帮忙看看能否兼容

**Comment by Vanessa219** [comment]
微信浏览器很难进行调试，外加没有浏览器输入地址。目前先不进行解决
