### ISSUE TITLE
pipe编辑已经置顶并且启用配图的帖子，保存提交不生效，并且启用配图和置顶选项没有给默认勾选

### ISSUE THREAD

**Issue by zhanghuilon2017** [b3log/pipe#116]
![g2ve 0wuq_i_o2gf0dg m7](https://user-images.githubusercontent.com/25762265/38766156-94496fe2-4000-11e8-88b9-f292525594d6.png)
![7cvp k qq3j67_ bru4e5mh](https://user-images.githubusercontent.com/25762265/38766157-a2314a1c-4000-11e8-8cad-fbc04ba9947f.png)
![0k d e7rv 8w1zmlm 0mw](https://user-images.githubusercontent.com/25762265/38766159-aada7206-4000-11e8-8d95-8923beee4e6e.png)

**Comment by zhanghuilon2017** [comment]
http://pipe.b3log.org/blogs/Ethan/articles/2018/04/14/1523692230638

**Comment by 88250** [comment]
启用配图那个是一次性的，每次勾选都会再添加一次。置顶的问题稍后就修复，谢谢！
