### ISSUE TITLE
独立账号体系

### ISSUE THREAD

**Issue by 88250** [b3log/pipe#117]
不依赖黑客派的登录，完全独立的账号体系。

如果你需要该特性，请投票，超过 50 赞就开工~

----

### 系分

* User 模型加入密码字段
* 加入注册/登录界面：
  * 社区：保持现有实现
  * 本地：用户名/密码
* https://github.com/b3log/pipe/issues/130

**Comment by amor520** [comment]
D大V武

**Comment by linkerlin** [comment]
已捐助100元, 希望能直接支持Github账号登录.

**Comment by Justice-love** [comment]
当时就是因为必须和黑客派强绑在一起所以直接忽略了，不是说黑客派不好，而是不喜欢这种捆绑营销。

**Comment by 88250** [comment]
@amorist @linkerlin 谢谢支持
@Justice-love 这是 B3log 计划： https://hacpai.com/b3log 当然，你要理解成**捆绑营销**我也没法子

**Comment by xdeng** [comment]
非常希望 不依赖与黑客派

**Comment by linkerlin** [comment]
能不能在Pipe和hacpai同时都支持Github账号登录呢.
这样,也可以打通,也可以独立.

**Comment by Justice-love** [comment]
github登陆强烈支持

**Comment by 88250** [comment]
@linkerlin 不同的 OAuth App 没法打通吧。

**Comment by linkerlin** [comment]
@88250 是不是可以通过Github的用户ID直接映射?

**Comment by 88250** [comment]
@linkerlin OAuth 回调的时候取不到 GitHub 全局唯一的 id，只能取到 open id，这个 open id 只是单个 oauth app 内唯一的。

**Comment by gitors** [comment]
@88250  如果用github 的登陆名或者邮箱呢？这个是不是唯一的

**Comment by 88250** [comment]
@gitors OAuth 取不到这样的敏感信息的。

**Comment by 88250** [comment]
谢谢大家参与投票，已经到达开工目标，v1.7.0 会加入这个改进！

**Comment by zanjs** [comment]
我要独立

**Comment by Justice-love** [comment]
希望以后能够有更多的PR，现在居然没有PR

**Comment by 88250** [comment]
@Justice-love 参与的人比较少 https://github.com/b3log/pipe/pulls?q=is%3Apr+is%3Aclosed

**Comment by gitors** [comment]
我倒是想pr ,奈何水平有限啊，尤其是go 还没入门，学习的计划也一直都是拖延了。
其实我在想， @88250  可以把一些待做的简单的东西交给社区的小伙伴门去做，自己做一些核心的东西就好了，比如有什么简单的修改啊，功能实现之类的，可以公开让hacpai社区 会员资源认领，然后 专人去开发，你最后做一下代码 review 再上线，留多点时间你去研究比较核心的东西。毕竟一个人的精力是有限的嘛，如果叫我们自己去做，然后pr 的话，事实上像我门大多数人根本无从下手。毕竟经验能力有限，目前大多数时候的工作都是按照安排来做的。

**Comment by 88250** [comment]
@gitors 提交代码只是贡献开源的一种方式，还有其他很多方式，比如帮助测试反馈，帮助项目宣传推广。对于提交代码而言，真正要提交的人就一定会提交，开源社区的协作方式不是安排下发任务，而是参与者们完全自发的协作。

推荐看下《大教堂与集市》，对开源有一些更深入的了解。

**Comment by gitors** [comment]
@88250 买了一本纸质书，打算研读一下

**Comment by 88250** [comment]
@gitors 看完记得用链书挂单 :trollface:

**Comment by Adrift001** [comment]
感觉这个无所谓,我比较在意是否是HTTPS.🙂

**Comment by gitors** [comment]
@Adrift001  https 跟代码没多大关系吧？

**Comment by 88250** [comment]
从 v1.8.7 开始仅支持通过 GitHub 登录，详情以及迁移方式可参考 #191 。
