### ISSUE TITLE
文章修改报错

### ISSUE THREAD

**Issue by localvar** [b3log/pipe#125]
提交以后重新提交就提示：UNIQUE constraint failed: b3_pipe_archives.id

**Comment by 88250** [comment]
有错误日志么？

**Comment by localvar** [comment]
没有，我的数据库用的是sqlite，从1.5 升级上来的

**Comment by 88250** [comment]
谢谢，这几天比较忙，可能要过几天才能看了。如果你有时间，也请帮忙 debug 一下，谢谢！

**Comment by localvar** [comment]
已提交 [PR#126](https://github.com/b3log/pipe/pull/126)

**Comment by localvar** [comment]
:hmm, 覆盖率降了一丁点，合并没问题吧

**Comment by 88250** [comment]
覆盖了没关系，已经给出修改建议，请看一下，谢谢！
