### ISSUE TITLE
编译缺失依赖

### ISSUE THREAD

**Issue by OneMuggle** [b3log/pipe#128]
![image](https://user-images.githubusercontent.com/26530847/41635939-12c19b90-747e-11e8-87e0-70b7f15b3962.png)

**Comment by 88250** [comment]
go path 没有配置对吧。

**Comment by OneMuggle** [comment]
重新clone代码，go path设置：
![image](https://img.hacpai.com/file/2018/06/dc553bdd309a48fe82ebf9ff99b4e876_gosetting.png)
编译：
![image](https://img.hacpai.com/file/2018/06/ad9c88a8241f4c69a62d36fc520bdad8_gobuild.png)

**Comment by 88250** [comment]
包路径没放对， src\github.com\b3log\pipe

**Comment by OneMuggle** [comment]
将vendor改为src目录，然后在github.com这个文件夹下创建了b3log\pipe文件夹，把提示缺失的拖进去，可以编译通过，但是这样不就破坏了项目路径，后面不能直接拉代码了？

**Comment by 88250** [comment]
为啥不能直接拉代码了？

**Comment by OneMuggle** [comment]
sorry，我理解错了
