### ISSUE TITLE
linux下运行npm run dev 报错。Cannot find module '@nuxtjs/youch'

### ISSUE THREAD

**Issue by mcflyanarkh** [b3log/pipe#135]
在 console 目录下，已经安装了 npm install。运行npm run dev 报错：
![image](https://user-images.githubusercontent.com/41098157/42549505-1abb9d64-84ff-11e8-9879-44af9bc4206c.png)
请教一下，这是什么原因。

**Comment by Vanessa219** [comment]
这个是 nuxt 的依赖。你把 node_modules 目录删了重新试一下。

**Comment by 88250** [comment]
我关闭 issue 了，如果还有问题请继续跟帖。
