### ISSUE TITLE
支持关闭本地注册

### ISSUE THREAD

**Issue by mufengcoding** [b3log/pipe#136]
1. 如何关掉注册
2. 或者注册用户如何管理

**Comment by 88250** [comment]
打算在 pipe.json 中增加一个配置项，用于配置是否开启注册，默认开启。

**Comment by mufengcoding** [comment]
这个比较合理 ，因为我是自建的pipe的 每个人过来都注册下，然后什么也没有，感觉怪怪的。对了评论是不是一定要注册后才能评论

**Comment by 88250** [comment]
评论是得注册后才能评论。
