### ISSUE TITLE
dockerfile maybe have a small problem

### ISSUE THREAD

**Issue by mufengcoding** [b3log/pipe#137]
Step 6/7 : RUN set -ex &&     apk --no-cache add ca-certificates &&     wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://raw.githubusercontent.com/sgerrand/alpine-pkg-glibc/master/sgerrand.rsa.pub &&     wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-${GLIBC_VERSION}.apk &&     apk add glibc-${GLIBC_VERSION}.apk &&     wget -O pipe${PIPE_VERSION}.zip https://github.com/b3log/pipe/releases/download/v${PIPE_VERSION}/pipe-${PIPE_VERSION}-linux-amd64.zip &&     unzip pipe${PIPE_VERSION}.zip &&     chmod +x pipe &&     rm -f pipe${PIPE_VERSION}.zip glibc-${GLIBC_VERSION}.apk
 ---> Running in 1526c400d994

+ apk --no-cache add ca-certificates
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
  ca-certificates (missing):
    required by: world[ca-certificates]
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)
ERROR: unsatisfiable constraints:
The command '/bin/sh -c set -ex &&     ap

**Comment by 88250** [comment]
有可能的话帮忙修复一下，谢谢！

**Comment by mufengcoding** [comment]
可能是我vps的镜像源问题，找到问题了，重启docker才可以，唉vps挂了没备份难受。如果有可能我觉的博客加个自动备份到百度云盘 蛮不错的

**Comment by 88250** [comment]
1. 用 SQLlite 的话备份一下数据库文件，用 MySQL 的话全量导出 SQL 文件
2. crontab 跑一下备份脚本，压缩后发邮箱
