### ISSUE TITLE
社区同步博客问题

### ISSUE THREAD

**Issue by 88250** [b3log/pipe#138]
从黑客派同步帖子回帖到博客有问题，需要修复。

**Comment by linkerlin** [comment]
我试一下.😂

**Comment by linkerlin** [comment]
似乎出错了:

[GIN-debug] [WARNING] Headers were already written. Wanted to override status code 200 with 500


2018/07/30 05:57:55 [Recovery] panic recovered:
PUT /api/console/articles/1532919646801 HTTP/1.0
Host: tujie8.net:80
Connection: close
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9,zh-TW;q=0.8,en;q=0.7
Connection: close
Content-Length: 840
Content-Type: application/json;charset=UTF-8
Cookie: UM_distinctid=162c5a459f379-023124651b5e4c-336c7b05-13c680-162c5a459f4c04; _ga=GA1.2.42650971.1531824538; Hm_lvt_306b94844f4eeb14030d76dc998b888f=1532069656,1532069936,1532077353,1532077361; pipe=MTUzMjkxOTU1NnxEdi1CQkFFQ180SUFBUkFCRUFBQV85VF9nZ0FCQm5OMGNtbHVad3dHQUFSa1lYUmhCbk4wY21sdVp3el90d0RfdEhzaVZVbEVJam94TENKVlRtRnRaU0k2SW14cGJtdGxjaUlzSWxWQ00wdGxlU0k2SWpFMU1UVTJORE00TVRNeU5UZ2lMQ0pWVW05c1pTSTZNaXdpVlVGMllYUmhjaUk2SW1oMGRIQnpPaTh2YVcxbkxtaGhZM0JoYVM1amIyMHZZWFpoZEdGeUx6RTBPRGd5TlRRNU5EUTROamhmTVRVeU5qWTBOekl6TlRNeE9DNGlMQ0pDU1VRaU9qRXNJa0pWVWt3aU9pSm9kSFJ3T2k4dmRIVnFhV1U0TG01bGRDOWliRzluY3k5c2FXNXJaWElpZlE9PXwOZl2Op4YoYqXkt-YDZrWw3OO7s0142VS0sNeksBydwQ==; _gid=GA1.2.1206057188.1532930213; Hm_lpvt_306b94844f4eeb14030d76dc998b888f=1532930250
Origin: http://tujie8.net
Referer: http://tujie8.net/admin/articles/post?id=1532919646801
Sec-Metadata: cause=forced, destination="", target=subresource, site=same-origin
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36
X-Real-Ip: 202.153.91.97


interface conversion: interface {} is nil, not string
/usr/local/go/src/runtime/panic.go:505 (0x4320a8)
        gopanic: reflectcall(nil, unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz), uint32(d.siz))
/usr/local/go/src/runtime/iface.go:244 (0x416ad8)
        panicdottypeE: panic(&TypeAssertionError{iface.string(), haveString, want.string(), ""})
/root/go/src/github.com/b3log/pipe/controller/console/articlectl.go:263 (0xa9e5be)
        UpdateArticleAction: Abstract:    arg["abstract"].(string),
/root/go/src/github.com/b3log/pipe/vendor/github.com/gin-gonic/gin/context.go:110 (0x94eb42)
        (*Context).Next: c.handlers[c.index](c)
/root/go/src/github.com/b3log/pipe/controller/console/authmidware.go:38 (0xa9ea60)
        LoginCheck: c.Next()
/root/go/src/github.com/b3log/pipe/vendor/github.com/gin-gonic/gin/context.go:110 (0x94eb42)
        (*Context).Next: c.handlers[c.index](c)
/root/go/src/github.com/b3log/pipe/vendor/github.com/gin-contrib/sessions/sessions.go:65 (0x9fa4ed)
        Sessions.func1: c.Next()
/root/go/src/github.com/b3log/pipe/vendor/github.com/gin-gonic/gin/context.go:110 (0x94eb42)
        (*Context).Next: c.handlers[c.index](c)
/root/go/src/github.com/b3log/pipe/vendor/github.com/gin-gonic/gin/recovery.go:46 (0x95db89)
        RecoveryWithWriter.func1: c.Next()
/root/go/src/github.com/b3log/pipe/vendor/github.com/gin-gonic/gin/context.go:110 (0x94eb42)
        (*Context).Next: c.handlers[c.index](c)
/root/go/src/github.com/b3log/pipe/vendor/github.com/gin-gonic/gin/gin.go:351 (0x955df4)
        (*Engine).handleHTTPRequest: c.Next()
/root/go/src/github.com/b3log/pipe/vendor/github.com/gin-gonic/gin/gin.go:318 (0x955632)
        (*Engine).ServeHTTP: engine.handleHTTPRequest(c)
/usr/local/go/src/net/http/server.go:2694 (0x6839bb)
        serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
/usr/local/go/src/net/http/server.go:1830 (0x67fb70)
        (*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
/usr/local/go/src/runtime/asm_amd64.s:2361 (0x45f4c0)
        goexit: BYTE    $0x90   // NOP

[GIN-debug] [WARNING] Headers were already written. Wanted to override status code 200 with 500

**Comment by 88250** [comment]
前端编译一下应该就好了，加了个摘要。

**Comment by linkerlin** [comment]
👌
