### ISSUE TITLE
首页 top 博客列表过滤未显示第一个博客

### ISSUE THREAD

**Issue by XPPA0215** [b3log/pipe#149]
**Describe the bug 描述问题**
在其他博客有发布2篇文章后，首页未显示初始化的博客，

**Expected behavior 期待的结果**
初始化的博客应该一直置顶显示？

**Desktop (please complete the following information): PC 端环境**
 - OS: [e.g. MAC OS]
 - Browser [e.g. chrome]
 - Version [e.g. 1.8.1]

**Comment by 88250** [comment]
首页只显示超过 5 篇文章的博客，具体过滤规则请看 https://github.com/b3log/pipe/issues/143 。

**Comment by XPPA0215** [comment]
> 首页只显示超过5篇文章的博客，具体过滤规则请看[＃143](https://github.com/b3log/pipe/issues/143)。
主页显示了其他的博客（非平台初始化时管理员的博客），且该博客文章只有两篇，当管理员博客在发布新的文章时（也未达到5篇）首页显示正常（管理员的博客）
