### ISSUE TITLE
mac编译报错  undefined: strings.Builder

### ISSUE THREAD

**Issue by yinxulai** [b3log/pipe#162]
### 描述问题
系统 mac 10.14.1
未做任何更改
在 controller/pjaxmidware.go:44:15 行中使用了 strings.Builder
但是我在godoc strings 中未找到该方法
同时编译也报错  controller/pjaxmidware.go:44:15: undefined: strings.Builder

我的确在百度中找到了strings.Builder 但是在go@1.9中确实不存在 我再去确认问题

**Comment by 88250** [comment]
golang SDK 用最新版。
