### ISSUE TITLE
无用标签清理

### ISSUE THREAD

**Issue by 88250** [b3log/pipe#184]

**Comment by Marveliu** [comment]
设置一个标签管理模块，当且仅当标签下面没有文章时，可以对文章进行清理。
还可以对功能扩展，例如对标签名称修改，以及从标签的维度查看文章列表。

**Comment by 88250** [comment]
标签在文章中是直接保存的标题，不是关联查询，所以要修改标签标题的话会很麻烦，建议不要做。
可以先从查询列表下手，这样可以熟悉程序结构，然后再考虑清理无用标签。

**Comment by Marveliu** [comment]
好的，我具体看一下

**Comment by Vanessa219** [comment]
- [ ] 添加搜索
- [ ] 分类下有标签时需进行提示，不能删除
- [ ] 提示需使用多语言
- [ ] 解决 database is locked 提示
- [ ] 移除编辑下拉按钮，直接使用删除按钮
