### ISSUE TITLE
har-validator@5.1.2包不存在

### ISSUE THREAD

**Issue by hhhizzz** [b3log/pipe#188]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[讨论区](https://hacpai.com/tag/solo)搜寻资料解决问题。

----

### 描述问题

编译时报的错误

> npm ERR! code E404
> npm ERR! 404 Not Found: har-validator@5.1.2

### 重现步骤

请描述如何重现这个问题：

直接使用build.sh编译，或者在theme里使用`npm install`

### 期待的结果

可以直接编译

### 桌面端环境

- OS: ubuntu 18.04

### 其他信息

检查到https://www.npmjs.com/package/har-validator 包确实不存在5.1.2版本，可以通过修改到5.1.3版本来修复

**Comment by Vanessa219** [comment]
https://github.com/b3log/pipe/blob/master/console/package-lock.json 

我们使用的是 5.1.3 版本，不行的话你重新装一下 node-sass@4.11.0 再试试
