### ISSUE TITLE
社区同步幂等处理

### ISSUE THREAD

**Issue by 88250** [b3log/pipe#193]
https://github.com/b3log/solo/issues/12629

完成后移除界面上的 B3 Key 更新，因为可以在发文时控制同步开关了，但系统底层尽量保证账号和社区的连接。

**Comment by 88250** [comment]
在文章列表上增加同步触发：

![image](https://user-images.githubusercontent.com/873584/52531410-0d94cd00-2d50-11e9-90a3-5cae011a0f7c.png)

**Comment by Vanessa219** [comment]
没有勾选同步也进行了同步
