### ISSUE TITLE
Emoji 支持改进

### ISSUE THREAD

**Issue by 88250** [b3log/pipe#207]
有的 emoji 不是 unicode 原生字符，而是图片资源，比如 :octocat: 需要进行支持以便和社区保持一致。

顺便支持滑稽表情 https://github.com/b3log/vditor/issues/16

**Comment by Vanessa219** [comment]
@88250 侧边栏最近评论中的 huaji 表情出不来

**Comment by 88250** [comment]
@Vanessa219 HTML 会被过滤，侧栏只保留纯文本，如果为空就略过了。
