### ISSUE TITLE
问一下 有从WordPress 迁移的方案么

### ISSUE THREAD

**Issue by Insofan** [b3log/pipe#215]
老的博客都在 WordPress 上 是markdown 格式 有什么方法可以快速迁移到这个平台？

**Comment by 88250** [comment]
你好，Pipe 支持导入 Markdown 文章，将已有文章打包压缩 zip，然后通过后台 -> 其他 -> 导入上传即可。Markdown 格式最好存在 Hexo 头或者 Jekyll 头，这样的话能够很好地还原日期、标题、摘要等元数据。
