### ISSUE TITLE
hacpai账号问题

### ISSUE THREAD

**Issue by zorkelvll** [b3log/pipe#226]
原有的hacpai账号zorke账号，因pipe博客升级之后只支持github登陆，现在用的是在hacpai中新的github账号导致原有zorke账号中的数据无法同步于是将其注销了，但是遗留下来的如下这张截图中的github中的博客设置地址还是原来的地址blog.caizhaoke.cn(现在这个域名地址是自己用域名解析隐形URL配置到www.zorkelvll.cn的)，该怎么解决掉将原来的地址进行更改？（问题根源在于http://pipe.b3log.org这个地方不支持了原有hacpai账号zorke去登录，然后无法去更改对应的首页设置地址了）

![image](https://user-images.githubusercontent.com/48007696/55288018-d6ec4200-53e3-11e9-8c94-393b2f306d10.png)

**Comment by 88250** [comment]
你好，是需要我们把 http://blog.caizhaoke.cn/ 这个域名从 pipe.b3log.org 上移除吗？

**Comment by zorkelvll** [comment]
> 你好，是需要我们把 http://blog.caizhaoke.cn/ 这个域名从 pipe.b3log.org 上移除吗？

可以更改为现在的域名https://www.zorkelvll.cn/ 嘛？

**Comment by 88250** [comment]
已经改好了，你看下是否还需要做什么调整。

**Comment by zorkelvll** [comment]
> 已经改好了，你看下是否还需要做什么调整。

暂时没有了，谢谢！！
