### ISSUE TITLE
markdown 无法预览

### ISSUE THREAD

**Issue by MrLaibin** [b3log/pipe#228]
### 描述问题

编辑文章时无法对markdown预览，console log提示
`POST http://localhost:5897/api/console/markdown net::ERR_CONNECTION_REFUSED`

### 重现步骤
未知
### 期待的结果
能够预览

### 截屏或录像

![image](https://user-images.githubusercontent.com/13825960/55300035-46a41080-5468-11e9-9c40-efd4329871e7.png)

基础配置、pipe.json的配置都未使用locahost

**Comment by 88250** [comment]
请看 https://hacpai.com/article/1552921022352/comment/1554085962692?r=88250
