### ISSUE TITLE
浏览器的前进后退会造成图片不加载

### ISSUE THREAD

**Issue by mrYuandq** [b3log/pipe#239]
浏览器的前进后退会造成图片不加载.

随便进入一个文章, 然后点浏览器的后退, 就会出现这个问题.
在次点进前进, 同样有这个问题.

目前我只看了两个主题: Gina, Next 至少这两个主题是有这样的问题的.

![image](https://user-images.githubusercontent.com/19283095/58420541-212a3080-80c0-11e9-8305-f4f9382ec144.png)

**Comment by mrYuandq** [comment]
@Vanessa219

**Comment by mrYuandq** [comment]
问题又出现啦.

![image](https://user-images.githubusercontent.com/19283095/59180501-b5ec5e00-8b97-11e9-9f14-a8228a8d34c0.png)

**Comment by Vanessa219** [comment]
![image](https://user-images.githubusercontent.com/970828/59201920-11394300-8bce-11e9-870a-52f4f8275fd1.png)
感觉可以的呀，disable cache 勾起来试试
