### ISSUE TITLE
manifest.json 文件出现跨域

### ISSUE THREAD

**Issue by mrYuandq** [b3log/pipe#241]
blog 中引入了 后台管理页面的 manifest.json 文件。
出现跨域问题。

![image](https://user-images.githubusercontent.com/19283095/59089289-521a2900-893c-11e9-8e64-ebbd5e9ae44b.png)

**Comment by 88250** [comment]
> blog 中引入了 后台管理页面的 manifest.json 文件。

这个操作我没看明白，麻烦详述一下，谢谢。

**Comment by mrYuandq** [comment]
![image](https://user-images.githubusercontent.com/19283095/59148087-8e31b480-8a36-11e9-902f-6c652bd29eaa.png)

现在博客地址和后台管理地址是两个不同的二级域名， 博客中引入了一个后台管理的文件。 manifest.json 跨域了。

**Comment by 88250** [comment]
docker 镜像已经更新，麻烦 pull 试试，谢谢。

**Comment by 88250** [comment]
Docker 镜像已经更新，请 pull 试试看是否修复，谢谢。

**Comment by mrYuandq** [comment]
D大, 这个文件是正常了， 但是文件内引用的图片找不到啊~

![image](https://user-images.githubusercontent.com/19283095/59165568-882ff680-8b50-11e9-825a-4bd2c690d7a5.png)

![image](https://user-images.githubusercontent.com/19283095/59165580-a0a01100-8b50-11e9-85f6-43acf7cadc3d.png)

**Comment by mrYuandq** [comment]
这个文件引入的应该是 后台地址的 logo@144.png 吧.  

博客二级域名地址是 blog.pilipala.co , 
后台的是 pipe.pilipala.co 

图片地址: 
正常: https://`pipe`.pilipala.co/theme/images/logo@144.png
404: https://`blog`.pilipala.co/theme/images/logo@144.png

而现在引用的就是那个 博客二级域名地址的logo文件 上面图片里能看的出来.

**Comment by 88250** [comment]
又进行了一次修复，麻烦 pull 试试看。

**Comment by 88250** [comment]
收到，目前还是有点问题，稍后再进行修复。

**Comment by mrYuandq** [comment]
OK,  D大辛苦~ 👍

**Comment by 88250** [comment]
又更新了一次，麻烦再试试看 😅

**Comment by mrYuandq** [comment]
OK 啦~ 👍
