### ISSUE TITLE
博客评论没有层级

### ISSUE THREAD

**Issue by gitors** [b3log/pipe#243]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[黑客派](https://hacpai.com)搜寻资料解决问题。

----

### 描述问题

文章回帖在社区是有明确的层级的，比如 我写的文章，A做了评论，B 回复了A的评论，能明确区分，但是在博客中，所以的评论/回复都是显示同级的，会让人不知所云，没有了上下文的联系，就跟在清风明月聊天一样。
（好像是只有社区同步过来的回复会这样，直接在博客回复是有层级的）

### 重现步骤
在社区评论、然后回复，再到博客查看评论结果。
### 期待的结果

希望社区同步到博客的评论，也能明确的体现出上下级关系。

### 截屏或录像

- 在博客直接回复
![image](https://user-images.githubusercontent.com/31715318/59811275-b923de80-933b-11e9-8ac0-d297e509770d.png)
- 社区同步过来的回复
![image](https://user-images.githubusercontent.com/31715318/59811287-c17c1980-933b-11e9-8257-4ce39a50d316.png)

### 桌面端环境

- OS: mac ox 10.14.5
- chrome 版本 75.0.3770.100（正式版本）
- Version 1.8.9

### 移动端环境

- Device: [e.g. iPhone8]
- OS: [e.g. iOS12]

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by 88250** [comment]
将在 #181 中进行处理，感谢反馈。

**Comment by gitors** [comment]
这个我之前提了。。我都忘记了

**Comment by 88250** [comment]
@gitors 说明这个 bug 非常影响体验 😂

**Comment by gitors** [comment]
@88250  确实，去看都时候突然发现不知道评论在说什么
