### ISSUE TITLE
数据库密码末位为 `!` 时会报错

### ISSUE THREAD

**Issue by JoeyGaojingxing** [b3log/pipe#255]
### 描述问题

请尽量清晰精准地描述你碰到的问题。
![image](https://user-images.githubusercontent.com/15071824/61846464-cd7a6e80-aed9-11e9-8a57-899fc4b806c0.png)

数据库密码末位为 `!` 时，bash 会报错。

`--mysql="root:xxxxxxx!@(127.0.0.1:3306)/pipe?charset=utf8mb4&parseTime=True&loc=Local"

**Comment by JoeyGaojingxing** [comment]
顺便，我在ubuntu上运行sqllite版也失败了，，，还在查找原因。启动后直接停止

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖反馈，谢谢。
