### ISSUE TITLE
docker 拉取镜像后 运行js路径不对

### ISSUE THREAD

**Issue by php403** [b3log/pipe#256]
![image](https://user-images.githubusercontent.com/32252481/62123637-f1371d80-b2fa-11e9-91ef-f55a169244b2.png)

**Comment by 88250** [comment]
启动的时候参数 `--server` 是否已经带上？

**Comment by php403** [comment]
![image](https://user-images.githubusercontent.com/32252481/62127195-0ebcb500-b304-11e9-9cc7-93ef88f0869e.png)
带上了 表也生成了

**Comment by php403** [comment]
我的问题。。。 我--server没设置
