### ISSUE TITLE
docker run error,ERROR 1709 (HY000): Index column size too large. The maximum column size is 767 bytes

### ISSUE THREAD

**Issue by jihuoguo290** [b3log/pipe#260]
ERROR 1709 (HY000): Index column size too large. The maximum column size is 767 bytes
set
 innodb_large_prefix 为 ON
still not work

**Comment by 88250** [comment]
你的 MySQL 是哪个版本？不是 5.7+ 的话需要升级一下。

**Comment by jihuoguo290** [comment]
5.6版本的

**Comment by 88250** [comment]
请升级到 5.7+ 问题应该就解决了。
