### ISSUE TITLE
登录后台反复授权, 无法进入后台管理

### ISSUE THREAD

**Issue by M2shad0w** [b3log/pipe#266]
### 描述问题
pipe 登录后台反复授权，无法进入管理后台
![image](https://user-images.githubusercontent.com/3387446/66463499-bf3af800-eaaf-11e9-8c53-b58eb5f825bf.png)
![image](https://user-images.githubusercontent.com/3387446/66463520-cc57e700-eaaf-11e9-9b76-c2ccb2f7ec34.png)

### 重现步骤

尝试地址
https://dataown.cn

**Comment by 88250** [comment]
请参考这里 https://github.com/b3log/pipe/issues/233
