### ISSUE TITLE
博客链接在微信中转发带图功能

### ISSUE THREAD

**Issue by M2shad0w** [b3log/pipe#267]
### 你在什么场景下需要该功能？

博客链接在微信中转发带图

**Comment by 88250** [comment]
麻烦仔细描述一下，没看懂 😂

**Comment by M2shad0w** [comment]
![分享带内容](https://user-images.githubusercontent.com/3387446/67154023-fbc7e880-f326-11e9-87cc-3fc31b3ef1c1.jpg)

**Comment by 88250** [comment]
收到，用户主页和文章详情页我们再试着看下是否能调整。我记得如果需要在分享时做到比较完美的效果是需要接入微信 API 的，通过 API 分享的话可以设置这些参数。

**Comment by M2shad0w** [comment]
是的，我也了解了以下，是要用微信的 jssdk 的。

**Comment by 88250** [comment]
刚刚确认了下，现在这个效果基本就是能够做到的最大努力了 😂
