### ISSUE TITLE
浏览器拦截不安全脚本

### ISSUE THREAD

**Issue by 468336329Zc** [b3log/pipe#268]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[黑客派](https://hacpai.com)搜寻资料解决问题。

----

### 描述问题

我给我的网站添加SSL证书后就这样
看我的地址   https://blog2.zhangchuanjun.cn/blogs/468336329Zc
会拦截css。。。。  需要我手动点击加载不安全脚本才能返回css。。

### 重现步骤

请描述如何重现这个问题：

1.https://certbot.eff.org/lets-encrypt/ubuntuxenial-nginx 进入此网站我给我的网站添加了安全证书
2.此后进入我的网站就会 拦截css  导致网站不正常
3.貌似手机端进入不会拦截，，。。。只有电脑进入会拦截  不知是不是我电脑端浏览器设置问题

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 桌面端环境

- OS: [e.g. windows, mac, linux]

### 移动端环境

- Device: [e.g. iPhone8]
- OS: [e.g. iOS12]

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by 88250** [comment]
`--server=` 是否改为 https？

**Comment by 468336329Zc** [comment]
> `--server=` 是否改为 https？

没有用。。。我重新启动了我的blog。。。 server改的是https://106.114......:5897     改成这样之后情况更糟糕。都不能弹出加载不安全脚本的选项了。。

**Comment by 88250** [comment]
--server 的值需要写你的域名，不是反代的 IP。
