### ISSUE TITLE
添加友情链接导航，自定义链接问题

### ISSUE THREAD

**Issue by nzmd** [b3log/pipe#273]
按照用户指南新建了一篇文章和导航用作友情链接，新建文章的链接是 日期/youlian  导航的链接是youlian 随后更新了文章的链接为youlian 发现文章页的导航链接还是旧的文章链接地址 首页上的导航是正确链接 似乎文章页的新建的导航用了相对路径？
复现网址：jieseclub.top
![首页导航](https://user-images.githubusercontent.com/21009810/69391943-4ca87380-0d0f-11ea-9f4a-e3d8fe8fb7e4.png)
![文章内页导航](https://user-images.githubusercontent.com/21009810/69391945-4d410a00-0d0f-11ea-8f83-451298a71f70.png)

**Comment by Vanessa219** [comment]
嗯，你把链接地址补全试一下。

**Comment by nzmd** [comment]
> 嗯，你把链接地址补全试一下。

可以了，感谢需要使用绝对路径
