### ISSUE TITLE
文章非登录浏览与 B3 同步问题

### ISSUE THREAD

**Issue by akkuman** [b3log/pipe#49]
如果不登陆黑客派，貌似是无法点击进入pipe博客文章内容页的

> 登录黑客派后访问 Pipe 就会自动创建一个博客。在 Pipe 上发布的文章将自动同步到黑客派上，这样能让更多人看到你创作的内容，更容易引起大家的关注和互动。

我在pipe用户指南中看到这个，但是我发布了博客之后并没有同步到黑客派上

**Comment by 88250** [comment]
谢谢反馈，已经确认是两个 bugs，稍后修复。

**Comment by 88250** [comment]
已经修复了。如果还没有同步到社区的文章是因为太短了，社区这么做了长度限制（512 字符）。

**Comment by akkuman** [comment]
谢谢啦，已经看到了
