### ISSUE TITLE
文章同步到黑客派后点击源链接404的bug

### ISSUE THREAD

**Issue by akkuman** [b3log/pipe#51]
**测试例子：**  

帖子地址：[https://hacpai.com/article/1514978295610](https://hacpai.com/article/1514978295610)  

点击源链接之后的跳转地址404：[http://pipe.b3log.org/articles/2018/01/01/1514814757482](http://pipe.b3log.org/articles/2018/01/01/1514814757482)  

博客真实地址：[http://pipe.b3log.org/blogs/Akkuman/articles/2018/01/01/1514814757482](http://pipe.b3log.org/blogs/Akkuman/articles/2018/01/01/1514814757482)

**Comment by 88250** [comment]
嗯，我也发现这个问题了，正在修 😅 
对了，以后就不在社区显示文章详情了，而是从列表直接跳转博客。

**Comment by 88250** [comment]
修复了，非常感谢反馈！
