### ISSUE TITLE
评论同步社区问题

### ISSUE THREAD

**Issue by Vanessa219** [b3log/pipe#70]
1. 作者的回帖会同步到 hacpai，但是没有头像
2. 删出回帖时，不会同步删除
3. 其他用户回帖不会同步到 hacpai

eg：
https://hacpai.com/article/1516082033308?p=1&m=1#1516257387035
http://vanessa.b3log.org/2018-web-roadmaps

**Comment by naiba** [comment]
刚才测试了一下，其他用户回帖不会同步到 hacpai
对于 hacpai 用户来说 pipe 是绝佳的选择

**Comment by 88250** [comment]
@naiba 回帖同步的问题下个版本解决，多谢帮忙
