### ISSUE TITLE
点击搜索后，样式不对

### ISSUE THREAD

**Issue by liangyuanpeng** [b3log/pipe#72]
![image](https://user-images.githubusercontent.com/28711504/35178756-64969b64-fdc8-11e7-8a26-84e07fb9314d.png)
如图，点击搜索框后，搜索按钮移动位置到中前部分了

**Comment by liangyuanpeng** [comment]
Google Chrome
版本 63.0.3239.132（正式版本） （64 位）

**Comment by 88250** [comment]
谢谢反馈，下个版本修复 😅
